Comparing numpy array with python list 

In [ ]:
import numpy as np
#to bring numpy library
import time

import sys 

l =range(1000)
#list with 1000 elements
print(sys.getsizeof(5)*len(l))
#to print the size = size of one element*length of list
array=np.arange(1000)
#to create numpy array , arange =to create elements 0 to 999
print(array.size*array.itemsize)
#to print the size of array

28000
8000


Comapring numpy is more convenient than python list

In [ ]:
import numpy as np 
import sys
import time

SIZE=1000000
l1=range(SIZE)
l2=range(SIZE)

a1=np.arange(SIZE)
a2=np.arange(SIZE)

#python list
start = time.time()
result = [ (x+y) for x,y in zip(l1,l2)]
print("python list took: ", (time.time()-start)*1000)
#numpy list
start=time.time()
result = a1 + a2
print("numpy took: " , (time.time()-start)*1000)

      


python list took:  134.33504104614258
numpy took:  19.730091094970703


one dimensional array

In [ ]:
import numpy as np
a=np.array([5,6,9])
a[0]


5

two dimensional array

In [ ]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
a.ndim
#to print the dimensions 

2

In [ ]:
import numpy as np
a=np.array([5,6,9])
a.ndim


1

In [ ]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
a.itemsize
#to print the dimensions 

8

iten size

In [ ]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]] , dtype=np.float64)
a.itemsize
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

size

In [ ]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
a.size

6

In [ ]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
a.size
a

array([[1, 2],
       [3, 4],
       [5, 6]])

shape

In [ ]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
a.shape

(3, 2)

In [ ]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]] , dtype=np.complex)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [ ]:
import numpy as np
np.zeros( ( 3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
import numpy as np
np.ones( ( 3,4) )

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
l=range(5)
l

range(0, 5)

In [ ]:
l[0]

0

In [ ]:
import numpy as np
np.arange(1,5)

array([1, 2, 3, 4])

In [ ]:
import numpy as np
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
a.reshape(2,3)


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [ ]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
a.min()

1

In [ ]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
a.max()

6

In [ ]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
a.sum()

21

In [ ]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
a.sum(axis=0)

array([ 9, 12])

In [ ]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
a.sum(axis=1)

array([ 3,  7, 11])

In [ ]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [ ]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
np.std(a)

1.707825127659933

In [ ]:
import numpy as np
b=np.array([[5,6] , [7,8]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
import numpy as np
n=[6,7,8]
n[0:2]

[6, 7]

In [ ]:
import numpy as np
n=[6,7,8]
n[-1]

8

In [ ]:
import numpy as np
a=np.array([6,7,8])
a[0:2]


array([6, 7])

In [ ]:
a=np.array([[6,7,8], [1,2,3], [9,3,2]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [ ]:
import numpy as np 
a=np.array([[6,7,8], [1,2,3], [9,3,2]])
a[-1,0:2]


array([9, 3])

In [ ]:
import numpy as np 
a=np.array([[6,7,8], [1,2,3], [9,3,2]])
a[:,1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])

In [ ]:
import numpy as np 
a=np.array([[6,7,8], [1,2,3], [9,3,2]])
for row in a:
  print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [ ]:
import numpy as np 
a=np.array([[6,7,8], [1,2,3], [9,3,2]])
for cell in a.flat:
  print(cell)

6
7
8
1
2
3
9
3
2


In [ ]:
import numpy as np 
a=np.array([[6,7,8], [1,2,3], [9,3,2]])
a=np.arange(6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
import numpy as np 
a=np.array([[6,7,8], [1,2,3], [9,3,2]])
a=np.arange(6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
import numpy as np 
a=np.array([[6,7,8], [1,2,3], [9,3,2]])
a=np.arange(6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [ ]:
import numpy as np 
a=np.array([[6,7,8], [1,2,3], [9,3,2]])
np.hsplit(a,3)


[array([[6],
        [1],
        [9]]), array([[7],
        [2],
        [3]]), array([[8],
        [3],
        [2]])]

In [ ]:
import numpy as np 
a=np.array([[6,7,8], [1,2,3], [9,3,2]])
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

run for loop

In [ ]:
import numpy as np
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
import numpy as np 
a=np.array([[6,7,8], [1,2,3], [9,3,2]])
b>4
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
import numpy as np
a=np.arange(12).reshape(3,4)
a
for row in a:
  print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
import numpy as np
a=np.arange(12).reshape(3,4)
a
for row in a:
  for cell in row:
      print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [ ]:
import numpy as np
a=np.arange(12).reshape(3,4)
a
for cell in a.flatten():
  print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [ ]:
import numpy as np
a=np.arange(12).reshape(3,4)
a

for x in np.nditer(a,order='F',flags=['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [ ]:
import numpy as np
a=np.arange(12).reshape(3,4)
for x in np.nditer(a,op_flags=['readwrite']):
  x[...]=x*x
  

In [ ]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
b=np.arange(3,15,4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

iterate 2 arrays

In [ ]:
for x,y in np.nditer([a,b]):
    print(x,y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11
